### ISSUE TITLE
Add iamInstanceProfile to VirtualMachine

### ISSUE THREAD

**Issue by ckelner** [TheWeatherCompany/dasein-cloud-core#32]
Can be found in the instance response when calling DescribeInstances see: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-ItemType-RunningInstancesItemType.html

Must be completed for TheWeatherCompany/grid-api#405

Edit: NOTE: AWS takes both an ARN and a Name, should we choose one or support both? http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-RunInstances.html

**Comment by ckelner** [comment]
@clstokes any idea what we should call this property on VirtualMachine ?

**Comment by ckelner** [comment]
@clstokes also: AWS takes both an ARN and a Name, should we choose one or support both? http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-RunInstances.html

**Comment by clstokes** [comment]
I think just the ARN and we should call it providerRoleId or something like that.

**Comment by ckelner** [comment]
I'm on board. :+1: thanks

**Comment by clstokes** [comment]
:sunglasses:
